[package]
name = "declarative-routeros"
version = "0.0.0"
edition = "2021"

[dependencies]
ssh2 = "*"
rpassword = "*"
tracing = "*"
tracing-core = "*"
tracing-subscriber = { version = "*", features = [ "env-filter" ] }
clap = { version = "4.4.18", features = ["derive"] }
